- name: Demo on reading inputs from user using vars_prompt
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL 
      private: no
  tasks:
    - name: Print URL
      debug:
        msg: "URL = {{URL}}"
